### ISSUE TITLE
Upgrading to 7.1.0 throws an error about operationOutput

### ISSUE THREAD

**Issue by nechama-z** [aoudiamoncef/apollo-client-maven-plugin#84]
Upgrading to 7.1.0 with no other changes gives an error on `generate-sources` 
`Execution default of goal com.github.aoudiamoncef:apollo-client-maven-plugin:7.1.0:generate failed: Apollo: operationOutput requires a manifest file`

I see this parameter was added but I'm not sure what the values should be

**Comment by aoudiamoncef** [comment]
Hi, try to disable It if you don't need it, as it's enabled by default

**Comment by nechama-z** [comment]
Perfect, that worked. Thank you @rruizt and @aoudiamoncef. 
(What would be needed to get the output to work properly? Is it something on my schema? Is there more information about this field anywhere?)

**Comment by rruizt** [comment]
In order to setup the operation manifest generation you need to also set the property `generateOperationDescriptors` to true.

```xml
<compilationUnit>
    <generateOperationDescriptors>false</generateOperationDescriptors>
    <compilerParams>
    ....
        <operationManifestFormat>persistedQueryManifest</operationManifestFormat>
    ....
    </compilerParams>
</compilationUnit>
```

You can check the valid formats [here](https://github.com/aoudiamoncef/apollo-client-maven-plugin/blob/3ee643eda62ba9acad0c925f15efe7e6dc563f11/apollo-client-maven-plugin/src/main/kotlin/com/github/aoudiamoncef/apollo/plugin/config/CompilerParams.kt#L88)
